### ISSUE TITLE
SigNoz website sidebar bug

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io#284]
https://www.loom.com/share/067dcf2b47bf48e78e77f704dc4c90de?sid=ab12fd30-7167-4d7e-b1a5-c8be21de6a9c

Creating this [issue](https://github.com/SigNoz/engineering-pod/issues/1368) from eng pod here for visibility.

@harshbutfairx can you look into this.

**Comment by ankit01-oss** [comment]
Adding more context here related to the same issue.

If a user lands up on our docs directly, let's say with this url: https://signoz.io/docs/userguide/manage-dashboards/ The side bar doesn't open up. The user won't have any idea on what section of the doc they are in. cc: @makeavish

**Comment by harshbutfairx** [comment]
This PR fixes the issue:

https://github.com/SigNoz/signoz-web/pull/322

**Comment by pranay01** [comment]
@harshbutfairx We should use github keywords so that an issue gets closed automatically if the corresponding PR is closed. Check this doc - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

cc @YounixM on may be letting Harsh  know about some of the best practices we follow
